config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'

  get 'questions/edit'
  get 'questions/show'

  get 'questions/new'
  get 'questions/:id', to: 'questions#show'
  get 'questions/:id/edit', to: 'questions#edit'

  get '/signup', to: 'signup#index'
  get '/login', to: 'home#index'
  post '/login', to: 'login#new'
  post '/signup', to: 'signup#new'
  get '/questions', to: 'questions#index'
  get '/logout', to: 'login#destroy'
  post 'questions/create'
  post 'questions/add_comment'

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_many :sub_comments, class_name: "Comment", foreign_key: 'parent_id'
  belongs_to :user, class_name: "User"
  PARENT_TYPE_BY_KEY = {
    question: 1,
    comment: 2
  }
  validates :content, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :comments, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :user, class_name: 'User'

  validates :content, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_authentic
    has_many :questions, class_name: 'Question', dependent: :destroy

    validates :name, presence: true
    validates :email, presence: true
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  attr_accessor :email, :password
  password_field(:password)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :check_session

  def check_session
    session = UserSession.find
    if session.blank?
      flash[:notice] = "Please Login first!"
      redirect_to '/' and return
    end
    @current_session = session
    @current_user = session.user
  end

  def record_not_found
    render file: "/public/404.html", layout: false
  end

  def current_session
    @current_session
  end

  def current_user
    @current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :check_session

  def index
    if current_user.present?
      redirect_to '/questions' and return
    end
    @user = User.new
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :check_session, only: :new

  def new
    if current_user.present?
      redirect_to '/questions' and return
    end
    user_params = filter_user_params
    user = User.find_by(email: user_params[:email])
    if user.nil?
      flash[:notice] = 'Not an existing user ! Please signup'
      redirect_to '/signup'
    else
      session = UserSession.new(user_params)
      if session.save
        redirect_to '/questions' and return
      end
      flash[:notice] = 'Invalid Password !'
      redirect_to '/' and return
    end
  end

  def destroy
    session = UserSession.find
    session.destroy
    redirect_to '/'
  end


  def filter_user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show]
  def index
    @questions = Question.all
  end

  def show
    @main_comments = Comment.where(parent_id: @question.id, parent_type: Comment::PARENT_TYPE_BY_KEY[:question]).includes(:user)
    @new_comment = Comment.new
  end

  def new
    @question = Question.new
  end

  def create
    question = Question.new(question_params)
    question.title = question.title + " ?" if question.title.present? && question.title.exclude?('?')
    question.user_id = @current_user.id
    unless question.save
      @question = question
      render "new" and return
    end
    redirect_to questions_index_path
  end

  def add_comment
    comment = Comment.new(comment_params)
    comment.user_id = @current_user.id
    unless comment.save
      flash[:notice] = "Unable to add comment !"
    end
    redirect_to "/questions/#{params.dig(:comment, :question_id)}"
  end

  private

  def load_question
    @question = Question.find_by(id: params[:id])
    if @question.blank?
      record_not_found and return
    end
  end

  def question_params
    params.require(:question).permit(:title, :content)
  end

  def comment_params
    params.require(:comment).permit(:parent_id, :content, :parent_type)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  skip_before_action :check_session

  def index
  end

  def new
    if current_user.present?
      redirect_to '/questions' and return
    end
    user_params = filter_user_params
    if User.find_by(email: user_params[:email])
      flash[:notice] = 'Email already exists ! Please login'
      redirect_to '/login'
    else
      user = User.new(user_params)
      user.active = true
      if user.save
        UserSession.create!(user)
        redirect_to '/questions'
      else
        flash[:notice] = user.errors.full_messages
        redirect_to '/signup'
      end
    end
  end


  def filter_user_params
    params.require(:user).permit(:email, :password, :name, :password_confirmation)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    session = UserSession.new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/home/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-error">
    <%= msg %>
  </div>
<% end %>
<div class='container'>
<h1 class="text-center"> Welcome to Forum</h1>
<div class="card card-login text-center">
<%= form_tag('/login', method: 'post') do %>
  <%= label_tag(:email, "Email")%><br>
  <%= email_field_tag "user[email]" %><br>
  <%= label_tag(:password, "Password")%><br>
  <%= password_field_tag "user[password]" %><br>
  </br>
  <%= submit_tag("Login") %>
<%end%>

  </br>
  </br>
<%= link_to('Not a member? Signup!','/signup') %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if @current_user.present? %>
<div class="navbar">
    <% if !(params[:action].eql?("index") && params[:controller].eql?("questions"))  %>
      <a href="/questions">< Back to Questions</a>
    <% end %>
    <% if !params[:action].eql?("new") %>
      <%= link_to('Create a new question', questions_new_path) %>
    <% end %>
  <div>
    <%= "#{@current_user.name} (#{@current_user.email})" %>
    <%= link_to('Logout','/logout') %>
  </div>
</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/questions/_comment_form.html.erb
<%= form_for @new_comment, as: :comment, url: {controller: :questions, action: 'add_comment' } do |f| %>
  <%= f.hidden_field :question_id, :value => "#{question_id}" %>
  <%= f.hidden_field :parent_id, :value => "#{parent_id}" %>
  <%= f.hidden_field :parent_type, :value => "#{Comment::PARENT_TYPE_BY_KEY[parent_type]}" %>
  <%= f.text_area :content %> </br></br>
  <%= f.submit %>&nbsp;&nbsp;
  <%= link_to 'Back', :back %>
<% end %>

app/views/questions/_form.html.erb
<div class="align_center">
  <h1><%= form_title %></h1>
</div>
<div class="align_center question_form">
  <%= form_for @question, as: :question, url: {controller: :questions, action: action } do |f| %>
    <div class="form_heading">Title</div>
    <%= f.text_field :title, class: 'form-title' %> </br></br>
    <div class="form_heading">Content</div>
    <%= f.text_area :content, :cols => 50, :rows => 10 %> </br></br>
    <%= f.submit %>&nbsp&nbsp
  <% end %>
</div>

app/views/questions/index.html.erb
<div class="container">
<h1 class="align_center question-heading">Questions</h1>
<% if @questions.present? %>
  <ul class="list-unstyled center-block question-block">
  <% @questions.each do |question| %>
    <li class="align_center question_li">
      <%= link_to(question.title,"/questions/#{question.id}") %>
    </li>
  <% end %>
  </ul>
<% else %>
    <%= link_to('Empty Here ! please create one', questions_new_path, class: "align_center") %>
<% end %>
</div>

app/views/questions/new.html.erb
<% if @question.errors.any? %>
  <div id="alert alert-error alert-dismissible">
    <h2><%= pluralize(@question.errors.count, "error") %> prohibited this task from being saved:</h2>

    <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<%= render partial: "form", locals: {action: 'create',form_title: 'Post a Question !'} %>

app/views/questions/show.html.erb
<h1 class="align_center"> <%= @question.title %></h1>
<div><p class="align_center">By <%= @question.user.name %></p></div>
<div class="question_section">
<p class="question-content"> <%= @question.content %></p>
<button data-toggle="collapse" data-target="#add_comment">Add Comment</button>
<div id="add_comment" class="collapse comment_form">
<%= render partial: "comment_form", locals: {parent_id: @question.id, parent_type: :question, question_id: @question.id} %>
</div>
</div>

<% if @main_comments.present? %>
<div class="comments_section">
<h3>All Comments</h3>
<ul class="list-unstyled comments_list">
<% @main_comments.each do |comment| %>
  <div class="comment_box">
  <li><%= comment.content %></li>
  <div><p>By <%= comment.user.name %></p></div>
  <% sub_comments = comment.sub_comments.includes(:user) %>
  <% if sub_comments.present? %>
    <button data-toggle="collapse" data-target="#sub_comments_section_<%= comment.id %>">Show Replies</button>
    <div id="sub_comments_section_<%= comment.id %>" class="collapse sub_comments_section">
      <% sub_comments.each do |sub_comment| %>
        <p class="sub_comment_data"> <%= sub_comment.content %></p>
        <div><p>By <%= sub_comment.user.name %></p></div>
      <% end %>
    </div>
  <% end %>
  <button data-toggle="collapse" data-target="#sub_comment_box_<%= comment.id %>">Add Reply</button>
  <div id="sub_comment_box_<%= comment.id %>" class="collapse comment_form">
    <%= render partial: "comment_form", locals: {parent_id: comment.id, parent_type: :comment, question_id: @question.id} %>
  </div>
   </div>
<% end %>
</ul>
</div>
<% end %>

app/views/signup/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-error">
    <%= msg %>
  </div>
<% end %>
<div class='container'>
<h1 class="text-center"> Welcome to Forum</h1>
  <div class="card card-login text-center">
<%= form_tag('/signup', method: 'post') do %>
  <%= label_tag(:first_name, "Name") %>
  </br>
  <%= text_field_tag "user[name]" %>
  </br>
  <%= label_tag(:email, "Email")%><br>
  <%= email_field_tag "user[email]" %><br>
  <%= label_tag(:password, "Password")%><br>
  <%= password_field_tag "user[password]" %><br>
  <%= label_tag(:password_confirmation, "Confirm Password")%><br>
  <%= password_field_tag "user[password_confirmation]" %><br>
  </br>
  <%= submit_tag("Signup") %>
<%end%>

  </br>
  </br>
<%= link_to('Already a member? Login!','/login') %>
  </div>
</div>